### ISSUE TITLE
Save stats when crt ActionReplay fastload is active, write protected file

### ISSUE THREAD

**Issue by radius75** [WebFritzi/Freecell64#1]
-delete stats file
-run game
-new game
-new game

when doing "overwrite" gives the mark write protect [<]

![obraz](https://user-images.githubusercontent.com/1929111/147980475-83cd169e-38c2-425e-b1d6-23f9e5286d80.png)
![obraz](https://user-images.githubusercontent.com/1929111/147980527-f551802b-077c-4eb6-9858-fdf5d88f2c0c.png)

**Comment by WebFritzi** [comment]
Thank you very much. I'll take care of it.

**Comment by radius75** [comment]
I used to program a little bit on c64.
Maybe it is enough to save with the combination of [@0: STATS] or better first SCRATCH file and SAVE (safer due to faulty DOS in old 1541 Drive) pointing to start and end address of STATS file

I don't really remember what these commands (STATS, P, RS: STATS) do in your code. But fastloaders lika AReplay may be misinterpreting this. 

greetings
![obraz](https://user-images.githubusercontent.com/1929111/147983905-5a1b642f-72c0-4e69-8c6d-61e78d4e119f.png)

**Comment by radius75** [comment]
Update:
hmm
It seems that the more the write damages random sectors on the floppy disk, it writes the wrong data
![obraz](https://user-images.githubusercontent.com/1929111/147984755-89576926-5469-4818-8276-cd0f52ffea3b.png)

**Comment by WebFritzi** [comment]
"or better first SCRATCH file and SAVE (safer due to faulty DOS in old 1541 Drive) pointing to start and end address of STATS file"

That's actually exactly what's happening. I've attached the code to this message.

I might go back to the @0-version anyway. It's faster.

**Comment by WebFritzi** [comment]
Hi radius, could you check it out now? I've changed the code. Jut start the PRG on the disk.

**Comment by radius75** [comment]
Hello
It's still the same. Unfortunately.

It can write to the standard SAVE"@0:name",8,1 (with the memory area indication)
And loading the usual LOAD"name",8,1 ?

Sample "Save":
`*=$1000
;
start_adr = $c000
end_adr   = $c100
;
          lda       #txt_end-txt
          ldx       #<txt
          ldy       #>txt
          jsr       $ffbd     ;SETNAM
;
          ldx       $ba       ;last used device number
          bne       jump      ;if <> 0 is present
          ldx       #$08
jump      ldy       #$01
          lda       #$00
          jsr       $ffba     ;SETLFS
;
          lda       #<start_adr
          sta       $c1       ;low byte start address for LOAD / SAVE (*)
          lda       #>start_adr
          sta       $c2       ;hig byte start address for LOAD / SAVE
          ldx       #<end_adr ;low byte end address
          ldy       #>end_adr ;hig byte end address
          lda       #$c1      ;Address (*) of zero page register holding start address of memory area to save
          jsr       $ffd8     ;SAVE
;
          bcs       error     ;if carry set, a load error has happened
          rts
;
error                         ;Akkumulator contains BASIC error code
          ;ldx       #$00
          ;stx       $d020
          rts
;
txt       text      "@0:save" ;filename for scratch and SAVE
txt_end`

**Comment by WebFritzi** [comment]
The new save routine goes as follows:
`save            LDA #fname_end-fname
                LDX #<fname
                LDY #>fname
                JSR $FFBD     ; call SETNAM
                LDA #$00
                LDX $BA       ; last used device number
                BNE skip
                LDX #$08      ; default to device 8
skip            LDY #$00
                JSR $FFBA     ; call SETLFS

                LDA #<Stats_Time0
                STA $C1
                LDA #>Stats_Time0
                STA $C2

                LDX #<Seconds
                LDY #>Seconds
                LDA #$C1      ; start address located in $C1/$C2
                JSR $FFD8     ; call SAVE
                BCS error    ; if carry set, a load error has happened
                RTS
error           ; Akkumulator contains BASIC error code
                RTS

fname           !text "@0:STATS,P,W"
fname_end`

**Comment by radius75** [comment]
This piece of code (in my previous post) I ran in Vice + AReplay many times and it did not damage the sectors of the floppy disk

**Comment by WebFritzi** [comment]
Ok, I compared our two methods. They almost didn't differ at all. I guess the main ppoint was the ",P,W" in my filenema string. Ok, the new prg has been compiled with your method. Could you please check it out?

**Comment by radius75** [comment]
I tested "new game" more than 10 times and it seems that the save is correct every time :)

**Comment by WebFritzi** [comment]
Thank you so much for the testing, radius. Have fun playing Freecell. A Solitaire game with the same looks will be finished soon, BTW.

**Comment by radius75** [comment]
fixed:)
